"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type Role = "new" | "member" | "trusted" | "moderator" | "admin" | "owner";
type Profile = { id:string; email:string; nickname:string; status:string; community_role:Role; subscription_tier:string; post_count:number; comment_count:number; joined_at:string; last_seen_at:string|null };
type Board = { id:string; name:string; slug:string; description:string; board_type:string; status:string; read_role:Role; write_role:Role; comment_role:Role; allow_comments:boolean; allow_attachments:boolean; require_approval:boolean; created_at:string };
type Audit = { id:string|number; action:string; target_type:string; target_id:string; reason:string|null; created_at:string };
type Tab = "overview" | "members" | "boards" | "logs";

const roleNames: Record<Role,string> = { new:"신규회원", member:"일반회원", trusted:"우수회원", moderator:"운영자", admin:"관리자", owner:"최고관리자" };
const mockProfiles: Profile[] = [
  {id:"demo-1",email:"trader01@example.com",nickname:"차트마스터",status:"active",community_role:"trusted",subscription_tier:"pro",post_count:32,comment_count:118,joined_at:"2026-07-18T03:00:00Z",last_seen_at:"2026-08-14T01:20:00Z"},
  {id:"demo-2",email:"coinwave@example.com",nickname:"코인웨이브",status:"active",community_role:"member",subscription_tier:"free",post_count:8,comment_count:21,joined_at:"2026-08-02T08:00:00Z",last_seen_at:"2026-08-13T22:15:00Z"},
  {id:"demo-3",email:"newfx@example.com",nickname:"FX새싹",status:"pending",community_role:"new",subscription_tier:"free",post_count:0,comment_count:1,joined_at:"2026-08-14T00:10:00Z",last_seen_at:null},
  {id:"demo-4",email:"marketpro@example.com",nickname:"마켓프로",status:"active",community_role:"moderator",subscription_tier:"vip",post_count:84,comment_count:302,joined_at:"2026-06-11T01:00:00Z",last_seen_at:"2026-08-14T01:30:00Z"},
];
const mockBoards: Board[] = [
  {id:"board-1",name:"공지사항",slug:"notice",description:"서비스 공지와 운영 안내",board_type:"notice",status:"active",read_role:"new",write_role:"admin",comment_role:"member",allow_comments:false,allow_attachments:false,require_approval:false,created_at:"2026-08-01T00:00:00Z"},
  {id:"board-2",name:"외환 시황",slug:"forex-analysis",description:"외환 시장 분석과 전략",board_type:"forex",status:"active",read_role:"new",write_role:"member",comment_role:"new",allow_comments:true,allow_attachments:true,require_approval:false,created_at:"2026-08-02T00:00:00Z"},
  {id:"board-3",name:"코인 분석",slug:"crypto-analysis",description:"암호화폐 시장 분석",board_type:"crypto",status:"active",read_role:"new",write_role:"member",comment_role:"new",allow_comments:true,allow_attachments:true,require_approval:false,created_at:"2026-08-03T00:00:00Z"},
];
const mockLogs: Audit[] = [{id:1,action:"member.role_changed",target_type:"profile",target_id:"demo-1",reason:"우수 분석 활동",created_at:"2026-08-14T00:30:00Z"},{id:2,action:"board.created",target_type:"board",target_id:"board-3",reason:"코인 커뮤니티 개설",created_at:"2026-08-13T10:00:00Z"}];

function date(value:string|null){return value ? new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value)) : "접속 없음"}

export default function AdminDashboard(){
  const [tab,setTab]=useState<Tab>("overview"); const [profiles,setProfiles]=useState(mockProfiles); const [boards,setBoards]=useState(mockBoards); const [logs,setLogs]=useState(mockLogs); const [session,setSession]=useState<Session|null>(null); const [mode,setMode]=useState<"demo"|"live">("demo"); const [notice,setNotice]=useState(""); const [roleTarget,setRoleTarget]=useState<Profile|null>(null); const [boardOpen,setBoardOpen]=useState(false); const [query,setQuery]=useState("");
  const load=useCallback(async(current:Session)=>{const res=await fetch("/api/admin/overview",{headers:{Authorization:`Bearer ${current.access_token}`}});if(!res.ok){setNotice((await res.json()).error??"관리자 데이터를 불러오지 못했습니다.");return}const data=await res.json();setProfiles(data.profiles);setBoards(data.boards);setLogs(data.logs);setMode("live");setNotice("실제 관리자 데이터에 연결됐습니다.")},[]);
  useEffect(()=>{const client=getSupabaseBrowserClient();if(!client)return;client.auth.getSession().then(({data})=>{if(data.session){setSession(data.session);void load(data.session)}});const {data}=client.auth.onAuthStateChange((_event,next)=>{setSession(next);if(next)void load(next);else setMode("demo")});return()=>data.subscription.unsubscribe()},[load]);
  const filtered=useMemo(()=>profiles.filter(p=>`${p.nickname} ${p.email}`.toLowerCase().includes(query.toLowerCase())),[profiles,query]);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const client=getSupabaseBrowserClient();if(!client)return setNotice("Supabase 설정이 없습니다.");const {data,error}=await client.auth.signInWithPassword({email:String(form.get("email")),password:String(form.get("password"))});if(error)return setNotice(error.message);if(data.session){setSession(data.session);await load(data.session)}}
  async function changeRole(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!roleTarget)return;const form=new FormData(event.currentTarget);const role=String(form.get("role")) as Role;const reason=String(form.get("reason"));if(reason.trim().length<2)return setNotice("변경 사유를 입력해 주세요.");if(mode==="live"&&session){const res=await fetch(`/api/admin/members/${roleTarget.id}/role`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({role,reason})});const data=await res.json();if(!res.ok)return setNotice(data.error);await load(session)}else{setProfiles(items=>items.map(p=>p.id===roleTarget.id?{...p,community_role:role}:p));setLogs(items=>[{id:Date.now(),action:"member.role_changed",target_type:"profile",target_id:roleTarget.id,reason,created_at:new Date().toISOString()},...items]);setNotice("프리뷰에서 등급을 변경했습니다.")}setRoleTarget(null)}
  async function createBoard(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const payload={name:String(form.get("name")),slug:String(form.get("slug")),description:String(form.get("description")),boardType:String(form.get("boardType")),readRole:String(form.get("readRole")),writeRole:String(form.get("writeRole")),commentRole:String(form.get("commentRole")),allowComments:Boolean(form.get("allowComments")),allowAttachments:Boolean(form.get("allowAttachments")),requireApproval:Boolean(form.get("requireApproval"))};if(!payload.name||!payload.slug)return setNotice("게시판 이름과 주소를 입력해 주세요.");if(mode==="live"&&session){const res=await fetch("/api/admin/boards",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)return setNotice(data.error);await load(session)}else{setBoards(items=>[...items,{id:`demo-${Date.now()}`,name:payload.name,slug:payload.slug,description:payload.description,board_type:payload.boardType,status:"active",read_role:payload.readRole as Role,write_role:payload.writeRole as Role,comment_role:payload.commentRole as Role,allow_comments:payload.allowComments,allow_attachments:payload.allowAttachments,require_approval:payload.requireApproval,created_at:new Date().toISOString()}]);setNotice("프리뷰에 게시판을 생성했습니다.")}setBoardOpen(false)}
  const stats={members:profiles.length,pending:profiles.filter(p=>p.status==="pending").length,paid:profiles.filter(p=>p.subscription_tier!=="free").length,boards:boards.filter(b=>b.status==="active").length};
  return <div className="admin-app"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><span>N</span><b>NP ADMIN</b></Link><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><i>⌂</i>대시보드</button><button className={tab==="members"?"active":""} onClick={()=>setTab("members")}><i>◎</i>회원 관리<b>{profiles.length}</b></button><button className={tab==="boards"?"active":""} onClick={()=>setTab("boards")}><i>▤</i>게시판 관리<b>{boards.length}</b></button><button className={tab==="logs"?"active":""} onClick={()=>setTab("logs")}><i>◷</i>운영 기록</button></nav><div className="admin-user"><span>A</span><div><b>{mode==="live"?session?.user.email:"Admin Preview"}</b><small>{mode==="live"?"연결된 관리자":"프리뷰 모드"}</small></div></div></aside>
  <main className="admin-main"><header className="admin-top"><div><p>COMMUNITY OPERATIONS</p><h1>{tab==="overview"?"운영 대시보드":tab==="members"?"회원 관리":tab==="boards"?"게시판 관리":"운영 기록"}</h1></div><div><span className={`admin-mode ${mode}`}><i/>{mode==="live"?"LIVE DATABASE":"PREVIEW DATA"}</span>{!session&&<form className="quick-login" onSubmit={login}><input name="email" type="email" placeholder="관리자 이메일" required/><input name="password" type="password" placeholder="비밀번호" required/><button>연결</button></form>}</div></header>{notice&&<div className="admin-notice"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
  {tab==="overview"&&<><section className="admin-stats"><article><span>전체 회원</span><strong>{stats.members}</strong><small>누적 가입자</small></article><article><span>승인 대기</span><strong>{stats.pending}</strong><small>확인 필요</small></article><article><span>유료 회원</span><strong>{stats.paid}</strong><small>Basic 이상</small></article><article><span>활성 게시판</span><strong>{stats.boards}</strong><small>운영 중</small></article></section><div className="admin-grid"><section className="admin-card"><div className="card-title"><div><span>NEW MEMBERS</span><h2>최근 가입 회원</h2></div><button onClick={()=>setTab("members")}>전체 보기 →</button></div><MemberTable profiles={profiles.slice(0,4)} onRole={setRoleTarget}/></section><section className="admin-card activity-card"><div className="card-title"><div><span>ADMIN ACTIVITY</span><h2>최근 운영 기록</h2></div></div><AuditList logs={logs}/></section></div></>}
  {tab==="members"&&<section className="admin-card wide"><div className="admin-tools"><div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="닉네임 또는 이메일 검색"/><select><option>전체 상태</option><option>정상</option><option>승인 대기</option><option>정지</option></select><select><option>전체 등급</option>{Object.entries(roleNames).map(([k,v])=><option key={k}>{v}</option>)}</select></div><button>CSV 내보내기</button></div><MemberTable profiles={filtered} onRole={setRoleTarget}/></section>}
  {tab==="boards"&&<section className="admin-card wide"><div className="card-title board-title"><div><span>BOARD MANAGEMENT</span><h2>게시판 목록</h2></div><button className="lime-button" onClick={()=>setBoardOpen(true)}>+ 새 게시판</button></div><div className="board-table"><div className="board-row head"><span>게시판</span><span>유형</span><span>읽기 권한</span><span>쓰기 권한</span><span>상태</span><span/></div>{boards.map(board=><div className="board-row" key={board.id}><span><b>{board.name}</b><small>/{board.slug}</small></span><span>{board.board_type}</span><span>{roleNames[board.read_role]}</span><span>{roleNames[board.write_role]}</span><span><i className="status-dot"/>활성</span><button>수정</button></div>)}</div></section>}
  {tab==="logs"&&<section className="admin-card wide"><div className="card-title"><div><span>AUDIT LOG</span><h2>관리자 작업 기록</h2></div></div><AuditList logs={logs}/></section>}</main>
  {roleTarget&&<div className="modal-backdrop"><form className="admin-modal" onSubmit={changeRole}><button type="button" className="modal-close" onClick={()=>setRoleTarget(null)}>×</button><span>CHANGE MEMBER ROLE</span><h2>회원 등급 변경</h2><div className="modal-member"><i>{roleTarget.nickname.slice(0,1)}</i><div><b>{roleTarget.nickname}</b><small>{roleTarget.email}</small></div><em>{roleNames[roleTarget.community_role]}</em></div><label>변경할 등급<select name="role" defaultValue={roleTarget.community_role}>{Object.entries(roleNames).map(([key,value])=><option value={key} key={key}>{value}</option>)}</select></label><label>변경 사유<textarea name="reason" placeholder="변경 사유를 기록해 주세요." minLength={2} maxLength={500} required/></label><p>모든 등급 변경은 관리자 작업 기록에 저장됩니다.</p><div className="modal-actions"><button type="button" onClick={()=>setRoleTarget(null)}>취소</button><button className="lime-button">등급 변경</button></div></form></div>}
  {boardOpen&&<div className="modal-backdrop"><form className="admin-modal board-modal" onSubmit={createBoard}><button type="button" className="modal-close" onClick={()=>setBoardOpen(false)}>×</button><span>CREATE BOARD</span><h2>새 게시판 만들기</h2><div className="form-grid"><label>게시판 이름<input name="name" placeholder="예: 외환 시황" required/></label><label>게시판 주소<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="forex-analysis" required/></label></div><label>설명<textarea name="description" placeholder="게시판의 목적을 설명해 주세요."/></label><div className="form-grid"><label>유형<select name="boardType"><option value="general">일반</option><option value="notice">공지</option><option value="qna">질문·답변</option><option value="forex">외환 분석</option><option value="crypto">코인 분석</option><option value="review">신호 후기</option><option value="private">전용</option></select></label><label>읽기 권한<RoleSelect name="readRole" value="new"/></label><label>쓰기 권한<RoleSelect name="writeRole" value="member"/></label><label>댓글 권한<RoleSelect name="commentRole" value="new"/></label></div><div className="board-options"><label><input name="allowComments" type="checkbox" defaultChecked/>댓글 허용</label><label><input name="allowAttachments" type="checkbox"/>첨부파일 허용</label><label><input name="requireApproval" type="checkbox"/>승인 후 공개</label></div><div className="modal-actions"><button type="button" onClick={()=>setBoardOpen(false)}>취소</button><button className="lime-button">게시판 생성</button></div></form></div>}</div>
}
function RoleSelect({name,value}:{name:string;value:Role}){return <select name={name} defaultValue={value}>{Object.entries(roleNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select>}
function MemberTable({profiles,onRole}:{profiles:Profile[];onRole:(p:Profile)=>void}){return <div className="member-table"><div className="member-row head"><span>회원</span><span>등급</span><span>구독</span><span>활동</span><span>가입일</span><span>상태</span><span/></div>{profiles.map(p=><div className="member-row" key={p.id}><span className="member-id"><i>{p.nickname.slice(0,1)}</i><span><b>{p.nickname}</b><small>{p.email}</small></span></span><span><em className={`role-badge ${p.community_role}`}>{roleNames[p.community_role]}</em></span><span>{p.subscription_tier.toUpperCase()}</span><span>글 {p.post_count} · 댓글 {p.comment_count}</span><span>{date(p.joined_at)}</span><span><i className={`status-dot ${p.status}`}/>{p.status==="active"?"정상":p.status==="pending"?"대기":"정지"}</span><button onClick={()=>onRole(p)}>등급 변경</button></div>)}</div>}
function AuditList({logs}:{logs:Audit[]}){return <div className="audit-list">{logs.map(log=><div key={log.id}><i>{log.action==="board.created"?"▤":"◎"}</i><span><b>{log.action==="board.created"?"게시판 생성":"회원 등급 변경"}</b><small>{log.reason||"사유 없음"}</small></span><time>{date(log.created_at)}</time></div>)}</div>}
